---

all:
  children:
    iosxr:
      hosts:
        iosxr1:
          ansible_host: 10.0.0.1
        iosxr2:
          ansible_host: 10.0.0.2
      vars:
        ansible_user: myuser
        ansible_ssh_private_key_file: /home/myuser/.ssh/id_rsa
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.iosxr.iosxr
        gather_facts: false
    cumulus:
      hosts:
        cumulus1:
          ansible_host: 10.0.0.3
        cumulus2:
          ansible_host: 10.0.0.4
      vars:
        ansible_user: cumulus
        ansible_sudo_pass: 'mysecretpassword'
    deploy:
      children:
        iosxr:
        cumulus:
